"""Merge multi-tier specs and write effective-spec.md, .spec-lock.yaml, .spec-compliance.yaml."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import yaml

from .parser import Override, Requirement


@dataclass
class LockEntry:
    tier: str
    repo: str
    path: str
    tag: str
    commit: str
    pulled_at: str


@dataclass
class ComplianceItem:
    tier: str
    capability: str
    requirement: str
    level: str
    status: str          # compliant | override_justified | override_missing
    justification: str


# ── Override matching ─────────────────────────────────────────────────────────

def _slug(text: str) -> str:
    """Normalise text to slug for loose matching."""
    return re.sub(r'[^a-z0-9\u4e00-\u9fff]+', '-', text.lower()).strip('-')


def _find_override(
    req: Requirement,
    overrides: List[Override],
) -> Optional[Override]:
    """Match an override to a requirement by ref or fuzzy name match."""
    req_slug = _slug(req.name)
    for ov in overrides:
        # Exact ref match: tier/capability/name
        ref_parts = ov.requirement_ref.split("/")
        if len(ref_parts) >= 3:
            ref_name = _slug("/".join(ref_parts[2:]))
            if ref_name == req_slug:
                return ov
        # Fallback: slug of display_name
        if _slug(ov.display_name) == req_slug:
            return ov
    return None


# ── Merging ───────────────────────────────────────────────────────────────────

def merge(
    tiers: List[Tuple[str, str, str, Dict[str, List[Requirement]]]],
    service_overrides: List[Override],
) -> Tuple[List[ComplianceItem], List[Requirement]]:
    """
    tiers: [(tier_name, tag, repo, {capability: [Requirement]})]
    Returns (compliance_items, all_requirements_with_metadata).
    """
    compliance: List[ComplianceItem] = []
    all_reqs: List[Requirement] = []

    for tier_name, tag, repo, cap_map in tiers:
        for capability, reqs in cap_map.items():
            for req in reqs:
                req.tier = tier_name
                req.version = tag
                all_reqs.append(req)

                if req.level != "must":
                    continue

                override = _find_override(req, service_overrides)
                if override is None:
                    status = "compliant"
                    justification = ""
                elif override.justification:
                    status = "override_justified"
                    justification = override.justification
                else:
                    status = "override_missing"
                    justification = ""

                compliance.append(ComplianceItem(
                    tier=tier_name,
                    capability=capability,
                    requirement=req.name,
                    level=req.level,
                    status=status,
                    justification=justification,
                ))

    return compliance, all_reqs


# ── Writers ───────────────────────────────────────────────────────────────────

STATUS_ICON = {
    "compliant": "✓",
    "override_justified": "⚠",
    "override_missing": "✗",
}

LEVEL_BADGE = {
    "must": "[must]",
    "should": "[should]",
    "may": "[may]",
}


def write_effective_spec(
    all_reqs: List[Requirement],
    compliance: List[ComplianceItem],
    output_path: Path,
    service_name: str = "",
) -> None:
    """Write openspec/merged/effective-spec.md."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    compliance_map = {
        (c.tier, c.capability, c.requirement): c for c in compliance
    }

    # Group by tier
    by_tier: Dict[str, Dict[str, List[Requirement]]] = {}
    for req in all_reqs:
        by_tier.setdefault(req.tier, {}).setdefault(req.capability, []).append(req)

    lines = [
        f"# Effective Spec{' — ' + service_name if service_name else ''}",
        f"> Generated by spec sync @ {now}",
        f"> Do not edit manually — run `spec sync` to regenerate.",
        "",
    ]

    for tier, caps in by_tier.items():
        for capability, reqs in caps.items():
            tag = reqs[0].version if reqs else ""
            lines.append(f"## [{tier}@{tag}] {capability}")
            lines.append("")
            for req in reqs:
                ci = compliance_map.get((req.tier, req.capability, req.name))
                if ci:
                    icon = STATUS_ICON.get(ci.status, "·")
                    header = f"### {icon} {LEVEL_BADGE[req.level]} {req.name}"
                    lines.append(header)
                    if ci.status == "override_justified":
                        lines.append(f"> **Override:** {ci.justification}")
                    elif ci.status == "override_missing":
                        lines.append("> **⚠ Override declared but justification is missing!**")
                else:
                    badge = LEVEL_BADGE.get(req.level, "[·]")
                    lines.append(f"### · {badge} {req.name}")
                # Include requirement body (skip the H3 header line)
                body_lines = req.content.splitlines()[1:]
                lines.extend(body_lines)
                lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def write_lock_file(entries: List[LockEntry], lock_path: Path) -> None:
    """Write openspec/.spec-lock.yaml."""
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "sources": [
            {
                "tier": e.tier,
                "repo": e.repo,
                "path": e.path,
                "tag": e.tag,
                "commit": e.commit,
                "pulled_at": e.pulled_at,
            }
            for e in entries
        ],
    }
    with open(lock_path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False)


def write_compliance_file(compliance: List[ComplianceItem], path: Path) -> None:
    """Write openspec/merged/.spec-compliance.yaml for spec check."""
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "requirements": [
            {
                "tier": c.tier,
                "capability": c.capability,
                "requirement": c.requirement,
                "level": c.level,
                "status": c.status,
                "justification": c.justification or None,
            }
            for c in compliance
        ],
    }
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False)
